/**
 * @file bg_sub.cpp
 * @brief Background subtraction tutorial sample code
 * @author Domenico D. Bloisi
 */

//opencv
#include "opencv2/imgcodecs.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/videoio.hpp"
#include <opencv2/highgui.hpp>
#include <opencv2/video.hpp>
//C
#include <stdio.h>
//C++
#include <iostream>
#include <algorithm>
#include <sstream>

using namespace cv;
using namespace std;


 class GMM
{
  public:
    void init(Mat frame,Rect region);
    Rect track(Mat image,Rect region);

  private:
      Mat image; //current frame
      Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
      Ptr<BackgroundSubtractor> pMOG2;
      Rect  rect_gmm; //MOG2 Background subtractor

};
